#ifndef _UART_DMA_INT_H
#define _UART_DMA_INT_H
#include "STD_Types.h"

#define  		 	USART_TXE			7
#define  		 	USART_RXNE			5

#define 			DMA1_Channel4_Enable 0
#define 			DMA1_Channel5_Enable 0

#define 			CGIF4 				12
#define 			CTCIF4 				13
#define 			CHTIF4 				14
#define				CTEIF4 				15
#define 			TCIF4  				13

#define 			CGIF5 				16
#define 			CTCIF5 				17
#define 			CHTIF5 				18
#define				CTEIF5 				19
#define 			TCIF5 				17

typedef enum
{
  FLASH_IDLE,
  FLASH_WAIT_FOR_CMD,
} FLASH_StateType;

#define DMA_Channel1_Configuration (CH1_MEM2MEM_STATE|CH1_PRIORITY_LEVEL|CH1_SRC|CH1_PRF_INC_MODE|CH1_MEM_INC_MODE|CH1_CIRCULAR_MODE|CH1_TRANSFER_ERROR_IRQ|CH1_TRANSFER_COMPLETE_IRQ|CH1_HALF_TRANSFER_IRQ)

#define DMA_Channel2_Configuration (CH2_MEM2MEM_STATE|CH2_PRIORITY_LEVEL|CH2_SRC|CH2_PRF_INC_MODE|CH2_MEM_INC_MODE|CH2_CIRCULAR_MODE|CH2_TRANSFER_ERROR_IRQ|CH2_TRANSFER_COMPLETE_IRQ|CH2_HALF_TRANSFER_IRQ)

#define DMA_Channel3_Configuration (CH3_MEM2MEM_STATE|CH3_PRIORITY_LEVEL|CH3_SRC|CH3_PRF_INC_MODE|CH3_MEM_INC_MODE|CH3_CIRCULAR_MODE|CH3_TRANSFER_ERROR_IRQ|CH3_TRANSFER_COMPLETE_IRQ|CH3_HALF_TRANSFER_IRQ)

#define DMA_Channel4_Configuration (CH4_MEM2MEM_STATE|CH4_PRIORITY_LEVEL|CH4_SRC|CH4_PRF_INC_MODE|CH4_MEM_INC_MODE|CH4_CIRCULAR_MODE|CH4_TRANSFER_ERROR_IRQ|CH4_TRANSFER_COMPLETE_IRQ|CH4_HALF_TRANSFER_IRQ)

#define DMA_Channel5_Configuration (CH5_MEM2MEM_STATE|CH5_PRIORITY_LEVEL|CH5_SRC|CH5_PRF_INC_MODE|CH5_MEM_INC_MODE|CH5_CIRCULAR_MODE|CH5_TRANSFER_ERROR_IRQ|CH5_TRANSFER_COMPLETE_IRQ|CH5_HALF_TRANSFER_IRQ)

#define DMA_Channel6_Configuration (CH6_MEM2MEM_STATE|CH6_PRIORITY_LEVEL|CH6_SRC|CH1_PRF_INC_MODE|CH6_MEM_INC_MODE|CH6_CIRCULAR_MODE|CH6_TRANSFER_ERROR_IRQ|CH6_TRANSFER_COMPLETE_IRQ|CH6_HALF_TRANSFER_IRQ)

#define DMA_Channel7_Configuration (CH7_MEM2MEM_STATE|CH7_PRIORITY_LEVEL|CH7_SRC|CH7_PRF_INC_MODE|CH7_MEM_INC_MODE|CH7_CIRCULAR_MODE|CH7_TRANSFER_ERROR_IRQ|CH7_TRANSFER_COMPLETE_IRQ|CH7_HALF_TRANSFER_IRQ)

void USART_Init(void);
void USART_DMA_TX(void);
void USART_DMA_RX(void);
void DMA_USART_RX_Test(void);

#include "Bit_Math.h"
#include "UART_reg.h"
#include "DMA_Config.h"
#include "DMA_reg.h"

#endif
